// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CheckboxWithValidation: typeof import('./components/inputs/CheckboxWithValidation/CheckboxWithValidation.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    InputWithValidation: typeof import('./components/inputs/InputWithValidation/InputWithValidation.vue')['default']
    PageTitle: typeof import('./components/layout/PageTitle/PageTitle.vue')['default']
    PageWithSearch: typeof import('./components/layout/PageWithSearch/PageWithSearch.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./components/layout/Toolbar/Toolbar.vue')['default']
    UserSearchForm: typeof import('./components/forms/user/UserSearchForm/UserSearchForm.vue')['default']
  }
}

export {}
